
spring.datasource.url=jdbc:mysql://localhost:3306/booktracker
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
server.port=8081
# Désactiver logs Hibernate
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF
