apiVersion: apps/v1
kind: Deployment
metadata:
  name: booktracker-backend
  namespace: booktracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
        - sh
        - -c
        - until nc -z db 3306; do echo "Waiting for MySQL..."; sleep 5; done
      containers:
      - name: backend
        image: sirineehkiri/booktracker-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://db:3306/booktracker?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
