apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: booktracker
spec:
  selector:
    app: backend                  # cible les pods avec le label app=backend
  ports:
  - protocol: TCP
    port: 8081                    # port du Service (interne au cluster)
    targetPort: 8081              # port du container Spring Boot
  type: ClusterIP                 # accessible uniquement à l'intérieur du cluster
