apiVersion: apps/v1
kind: Deployment
metadata:
  name: booktracker-frontend
  namespace: booktracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sirineehkiri/booktracker-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80       # Nginx écoute sur le port 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
