apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: booktracker
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080               # port accessible depuis ta machine (30000-32767)
  type: NodePort                  # exposé à l'EXTÉRIEUR du cluster
