---
- name: Désactiver le swap
  command: swapoff -a
  ignore_errors: yes

- name: Désactiver swap dans fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'
  ignore_errors: yes

- name: Charger les modules kernel
  modprobe:
    name: "{{ item }}"
  loop:
    - overlay
    - br_netfilter

- name: Configurer le réseau
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    reload: yes
  loop:
    - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }
