server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Fix Angular routing - renvoyer index.html pour toutes les routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend Spring Boot
    location /api/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Cache pour les assets statiques
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
