server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Fix Angular routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy auth
    location /auth/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy books
    location /books/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/books/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy API
    location /api/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy uploads
    location /uploads/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/uploads/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy reading
    location /reading/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/reading/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy reviews
    location /reviews/ {
        proxy_pass http://backend-service.booktracker.svc.cluster.local:8081/reviews/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Cache assets statiques
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
