import { course } from './course';

export const courseList: course[] = [
  {
    Id: 1,
    courseType: 'primary',
    courseFramework: 'Apivia',
    Time: '30 min',
    courseName: 'Vitamin pro 3',
    Update: 'Updated 21 Jan 2020',
  },
  {
    Id: 2,
    courseType: 'primary',
    courseFramework: 'Apivia',
    Time: '90 min',
    courseName: 'Sakifo 3',
    Update: 'Updated 25 Jan 2020',
  },
  {
    Id: 3,
    courseType: 'warning',
    courseFramework: 'Zénio',
    Time: '30 min',
    courseName: '2MA essentiel',
    Update: 'Updated 30 Jan 2020',
  },
  {
    Id: 4,
    courseType: 'error',
    courseFramework: 'Néoliane',
    Time: '50 min',
    courseName: 'Hospi max',
    Update: 'Updated 01 Feb 2020',
  },
  {
    Id: 5,
    courseType: 'warning',
    courseFramework: 'Zénio',
    Time: '120 min',
    courseName: '2MAAttitude',
    Update: 'Updated 15 Feb 2020',
  },
  {
    Id: 6,
    courseType: 'warning',
    courseFramework: 'Zénio',
    Time: '60 min',
    courseName: '2MAPrévilège',
    Update: 'Updated 16 Feb 2020',
  },
  {
    Id: 7,
    courseType: 'primary',
    courseFramework: 'Apivia',
    Time: '90 min',
    courseName: 'Vitamin 3',
    Update: 'Updated 18 Feb 2020',
  },
  {
    Id: 8,
    courseType: 'primary',
    courseFramework: 'Apivia',
    Time: '150 min',
    courseName: 'Sakifo pro 3',
    Update: 'Updated 20 Feb 2020',
  },
  {
    Id: 9,
    courseType: 'error',
    courseFramework: 'Néoliane',
    Time: '80 min',
    courseName: 'Hospi',
    Update: 'Updated 21 Feb 2020',
  },
];
