[master]
18.206.220.213 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/labsuser.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[workers]
32.198.123.217 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/labsuser.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[all:vars]
ansible_python_interpreter=/usr/bin/python3
