---
# PLAY 1 : Installer K3s sur le Master
- name: Installer K3s Master
  hosts: master
  become: yes
  tasks:
    - name: Installer K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Attendre que K3s soit prêt
      wait_for:
        path: /var/lib/rancher/k3s/server/node-token
        timeout: 120

    - name: Récupérer le token K3s
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Sauvegarder le token
      set_fact:
        k3s_node_token: "{{ k3s_token.stdout }}"

    - name: Créer dossier .kube pour ubuntu
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu

    - name: Copier kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        mode: '0644'

# PLAY 2 : Installer K3s Agent sur le Worker
- name: Installer K3s Worker
  hosts: workers
  become: yes
  tasks:
    - name: Installer K3s agent
      shell: |
        curl -sfL https://get.k3s.io | \
        K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443 \
        K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_node_token'] }} \
        sh -
      args:
        creates: /usr/local/bin/k3s

# PLAY 3 : Vérifier le cluster
- name: Vérifier le cluster K3s
  hosts: master
  become: yes
  tasks:
    - name: Attendre que les nodes soient prêts
      shell: k3s kubectl get nodes | grep -c Ready
      register: ready_nodes
      retries: 10
      delay: 15
      until: ready_nodes.stdout | int >= 2

    - name: Afficher les nodes
      command: k3s kubectl get nodes
      register: nodes

    - name: Résultat
      debug:
        msg: "{{ nodes.stdout }}"
